[mcp_servers.binlog]
command = "dotnet"
args = [
    "dnx",
    "Microsoft.AITools.BinlogMcp",
    "--yes",
    "--prerelease",
]

[mcp_servers.mssql]
command = "npx"
args = [
    "-y",
    "mssql-mcp-server",
]

[mcp_servers.mssql.env]
MSSQL_CONNECTION_STRING = "Server=localhost;User Id=sa;Password=Hello123#;Database=clean_architect;trustServerCertificate=True;"
